### ISSUE TITLE
Implementing findNewHouse(*) 

### ISSUE THREAD

**Issue by AtiyahElsheikh** [MRC-CSO-SPHSU/LoneParentsModel.jl#100]

**Comment by AtiyahElsheikh** [comment]
Initially I have an impression that an optimal algorithm should maintain static lists of empty houses for each town to be updated by need. This would add an overhead to the implementation. First thoughts, this could be done either

-  internal to the data structure by additional fields to unoccupied houses (not favored because not necessarily every simulation process needs such information)
- Or new type of Town with additional data fields (occupiedHouses, unocuupiedHouses)
- Or static global / local variables / data structures maintaining such information (this could be also thought for subpopulation) 

My currently favorite approach is to follow the naive way without additional overhead efforts (i.e. set of empty houses are re-computed in every iteration) for the following reasons:

- I don't really know if Julia compiler does some hidden optimizations , e.g. reuse of computed local variables in a function from the last iteration
- the initial goal is correctness / precision of results. Later on after finishing this stage of translation, a profiler could be executed and optimization potentials can be prioritized

**Comment by AtiyahElsheikh** [comment]
prioritize optimization potentials across all algorithms and not just findNewHouse()

**Comment by mhinsch** [comment]
I doubt that the compiler will insert caching of local variables across function calls, but I agree with you that a naive implementation is totally fine for now.

**Comment by mhinsch** [comment]
I just encountered a very similar problem during the implementation of marriages (length of age classes is needed for every single call to `marriage!`). I think the easiest and least intrusive solution to both problems might be to use memoisation. It's not difficult to implement manually, but there's already a nice [package](https://github.com/marius311/Memoization.jl) that should do exactly what we need. 

So, in your case you would for example memoise the function `getEmptyHouses(houses)`. This would then compute the list of houses on the first call and afterwards just return it. There are two important things to keep in mind, though. First, the list of empty houses needs to be modified by the function calling `getEmptyHouses` (as it's not going to be recalculated). And second, depending on what else happens in the simulation it might be necessary to clear the cache (using `empty_cache!`) now and then.

**Comment by AtiyahElsheikh** [comment]
I will have a look over it. 

I was just thinking to have global typed variable(s) using the newest Feature of Julia 1.8.1 to be maintained every iteration. Not sure here if global typed variables still not recommended in the context of performance.

**Comment by mhinsch** [comment]
I think this is solved, marking for deletion.
