### ISSUE TITLE
rethink `independent`

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#114]
Seems a bit of a kludge at the moment.

**Comment by AtiyahElsheikh** [comment]
not yet so familiar with what "independent" means. If it is just regarding age and family structure, then it naturally belongs to kinshipBlock. But if income plays a role, it would probably belong to a higher-level.

**Comment by AtiyahElsheikh** [comment]
The other question if it makes sense/ is worth to replace a field with a function isIndependent(*)
