### ISSUE TITLE
check correctness of `movePeopleToEmptyHouse`

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#115]
`movePeopleToEmptyHouse` assumes the first person in the person list to be the one that determines where to look for an empty house. I'm not sure if that's in line with the original code for all instances where the function is called.

**Comment by AtiyahElsheikh** [comment]
Probably, I am influenced by do Divorces where a divorced person to move may be attached with children.
