### ISSUE TITLE
efficient parameters

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#12]
Currently parameters are of type `Dict{Symbol, Any}`, which is extremely inefficient, as a) Dicts are slow and b) the value type is `Any` and therefore potentially all code that uses parameters becomes type unstable.
The *syntax* of parameter access can be changed to `pars.value` without any loss in generality (if desired property access can be overloaded so that a Dict could still be used as a backend). This way the simulation functions themselves can remain agnostic as to which type parameters have and the frontend can decide which implementation to use.
Generally, I think, however, that there are few situations where a Dict is the best choice.

**Comment by AtiyahElsheikh** [comment]
I suggest to assign this issue to milestone 2.0, i.e. post optimization of first prototype? 

the properties dictionary comes from Agents.jl. So it will remain there at the moment. It still has some useful use-cases (where properties are not excessively accessed during model simulation). For other use-cases, e.g. heavily accessed parameters, variables etc.  In section 4 of design document (V0.3) an initial proposal is suggested, to attach separate variable-size lists of variables, parameters, etc. to the agents, or ABM or MABM structs. The definition of identifiers could look as follows: 

```
abstract type AbstractIdentifier end
abstract type AbstractVariable <: AbstractIdentifier end
...
mutable struct Variable{T} <: AbstractVariable
   identity::string
   val::T
   # ...
end
...
# A contract for any agent subtype:
function addVariable!(agent::AbstractSocialAgent, var::AbstractVariable,initVal) end
function addParameter!(agent::AbstractSocialAgent, par::AbstractParameter,val) end
function addConstant!(agent::AbstractSocialAgent, cst::AbstractConstant,val) end
function deleteVariable!(agent::AbstractSocialAgent, var::AbstractVariable) end
```

**Comment by mhinsch** [comment]
I think this is done
