### ISSUE TITLE
remove unnecessary types

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#13]
At the moment most functions seem to have explicitly typed parameters. Unless it is specifically known that a function only works for *one* type it is usually better to omit types.

**Comment by AtiyahElsheikh** [comment]
At the moment there is only one [Person type](https://github.com/MRC-CSO-SPHSU/LoneParentsModel.jl/blob/main/src/agents/Person.jl) and [AbstractPerson type](https://github.com/MRC-CSO-SPHSU/LoneParentsModel.jl/blob/main/src/agents/AbstractPerson.jl). I guess there will be more and more Person subtypes. 

Would you prefer 

```Julia
function removeDead!(person::P, population::ABM{P}) where {P}
```

over 

```Julia
function removeDead!(person::P, population::AbstractPerson)
```
?

**Comment by mhinsch** [comment]
I think the rule of thumb would be: leave out types unless necessary. removeDead is a bit of a borderline case in that you could leave out the types completely but on the other hand making the function generic (i.e. the version with the type parameter) makes the invariant (person and element of population have to be the same type) explicitly part of the interface.
Personally, I would probably leave out types even in this case (so: `removeDead!(person, population)) and maybe add an assertion in the function body.

**Comment by AtiyahElsheikh** [comment]
Actually this what the function kill_agent! does (from Agents.jl)

```julia
"remove an agent"
kill_agent!(agent,model::AbstractABM) = removefirst!(model.agentsList,agent) 
```
Then it makes sense to have 
```julia
"remove an agent"
kill_agent!(agent::P,model::ABM{P}) where {P} = removefirst!(model.agentsList,agent) # or kill_agent!(agent,model) (if Agents.jl is used)
```

I would still introduce removeDead! as: 

```julia
removeDead!(person::[Abstract]Person, abm) 
```

Then I am restricting this function only to be applied on Person types, while the other function kill_agent! (from Agents.jl) is available anyway.

**Comment by AtiyahElsheikh** [comment]
I would also think about introducing a module Population as a compensation for static type declaration. In this case the extra type safety would look more excessive and can be replaced by the duck-typing style (i.e. no static type Declaration)

**Comment by mhinsch** [comment]
> But in general I appreciate type safety at this development stage (still it is fine to remove unnecessary static typing as much as possible). Julia compiler provides sometimes ugly error messages. Thus I would really appreciate to have an error message like that , ... the closest list of candidates are
> 
> ```julia
> foo(::X,::Y)
> foo(::X,::Z)
> ... 
> ```

Fair enough. Let's keep the types for now then as long as that doesn't interfere with issue #19.

**Comment by AtiyahElsheikh** [comment]
I have added the following requirement in the document design: 

> Static types of function arguments is desired as a matter of safety and improved error messages, still duck-typing and shortest specification shall be applied as often as possible
