### ISSUE TITLE
Dead Person type

### ISSUE THREAD

**Issue by AtiyahElsheikh** [MRC-CSO-SPHSU/LoneParentsModel.jl#135]
Seems there could be a need to (optionally) store dead people (e.g. for statistical purposes). Therefore it could make sense to introduce a new immutable type for a deadPerson, e.g. 

```
struct DeadPerson 
  person:: Person 
  deathDate :: DateType   
end 
```

**Comment by AtiyahElsheikh** [comment]
Optionally, because for performance and memory consumption reasons, simulations without such a need can be made enabled.

**Comment by AtiyahElsheikh** [comment]
Just saw, related to #116

**Comment by mhinsch** [comment]
We do have the latest age for each agent, so instead of creating a new type I'd rather store the birth date in the basic info (then we could infer death date).

**Comment by AtiyahElsheikh** [comment]
Just came to my thought. 
This is the idea of having a new type, otherwise, why to store additional data we won't need them in all possible simulation studies.

**Comment by mhinsch** [comment]
Either way, I think that's a problem that can be solved when it occurs.
