### ISSUE TITLE
Performance with logging , input files , 

### ISSUE THREAD

**Issue by AtiyahElsheikh** [MRC-CSO-SPHSU/LoneParentsModel.jl#138]
Memory allocation increased a lot after using logging etc. Not sure if this is the only cause, as I was using the recent version of Simulate before modification.

For insuring I am creating a light version without  I/O, logging etc.

**Comment by AtiyahElsheikh** [comment]
I believe I have used once code_warntype on doDeaths! and the only (yellow light) warning was the combination of {Nothing,Person}

**Comment by mhinsch** [comment]
> I believe I have used once code_warntype on doDeaths! and the only (yellow light) warning was the combination of {Nothing,Person}

We might want to change this to using a Nobody constant (equivalent to UndefinedHouse) at some point.
