### ISSUE TITLE
Demography Data

### ISSUE THREAD

**Issue by AtiyahElsheikh** [MRC-CSO-SPHSU/LoneParentsModel.jl#142]
As mentioned in a comment within mainHelpers.jl, demographydata.jl needs to be placed within a module. 

I see two options: 
- as it is related to ParamTypes, it fits there
- or another module for Data 

Although currently not that significant amount of code within demographydata.jl, it makes sense to have a module for Data

**Comment by AtiyahElsheikh** [comment]
repeated in #147

**Comment by mhinsch** [comment]
> As mentioned in a comment within mainHelpers.jl, demographydata.jl needs to be placed within a module.
> 
> I see two options:
> 
>     * as it is related to ParamTypes, it fits there
> 
>     * or another module for Data
> 
> 
> Although currently not that significant amount of code within demographydata.jl, it makes sense to have a module for Data

Why does it need to be placed within a module?
