### ISSUE TITLE
keyword parameters

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#143]
KP are a bit of a nuisance for internal functions, so my suggestion would be to limit their use to user-facing functions with a lot of optional parameters.

**Comment by AtiyahElsheikh** [comment]
Completely fine with that. 

If I come over a situation where it still look useful, I would list it here.

**Comment by AtiyahElsheikh** [comment]
Will overtake this
