### ISSUE TITLE
selectMarraige

### ISSUE THREAD

**Issue by AtiyahElsheikh** [MRC-CSO-SPHSU/LoneParentsModel.jl#156]
```
selectMarriage(p, pars) = isMale(p) && isSingle(p) && age(p) > pars.ageOfAdulthood && careNeedLevel(p) < 4
```

apparently, alive(p) is missing?

**Comment by mhinsch** [comment]
Indeed, same for `shareMenNoChildren` in the same file. I'm surprised this hasn't caused any issues anywhere else.
