### ISSUE TITLE
consistent naming convention

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#16]
Currently camelCase and snake_case are both used. Personally I prefer CamelCase for types and snake_case for functions and variables, but whatever we choose it should be consistent.

**Comment by AtiyahElsheikh** [comment]
Personally I prefer removeDead! over remove_dead!. (DP in Julia author prefer the underscore). 

Recently I added a requirement to follow the same naming guidelines from Agents.jl. From the design document: 

> **Requirement 6** Naming and coding conventions from the package Agents.jl shall be adopted
> This is desired for the users of Agents.jl, in case future extension of a more sophisticated package is established. Some of the naming conventions are as follows:
> • types begin with a capital letter and words are connected, e.g. AbstractAgent
> • a method name is composed of small letters, e.g. run!(model) and composite name is usually separated with an underscore, e.g. agent_step!
> • a variable name is composed of small letters
> • ... 

We could also removeDead! while reducing the incosistancy originating from Agents.jl , e.g. 

```julia 
killAgent!(agent,abm) = kill_agent!(agent,abm) 
```
?
