### ISSUE TITLE
formalised structure for assumptions

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#17]
Come up with a way  to add assumptions to the code so that:
* they will automatically be tested
* they can include additional information
* all assumptions can easily be extracted from the code

**Comment by AtiyahElsheikh** [comment]
Macros?

**Comment by mhinsch** [comment]
It's easy to come up with a macro for that, maybe similar to `@test`. The main issue is point 3 - extracting all assumptions from the code in a straightforward manner. I'll have to think about that for a bit.

**Comment by mhinsch** [comment]
I have thought about this quite a bit and I think there is no good solution that wouldn't require substantial changes in coding style. The other issue is that it's not trivial to decide what counts as an assumption in a given situation. So, given that the function documentation we are now writing mostly solves the problem of having to be able to communicate with domain experts and that we are in a bit of a hurry I vote for dropping this and sticking to plain assertions and unit tests for now.
