### ISSUE TITLE
rename declare?

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#18]
This is obviously bikeshedding, but declaration has a very specific meaning in the context of statically typed languages, so maybe we could use create or something like that.

**Comment by AtiyahElsheikh** [comment]
I am fine with that. 
In my mind in case a mini-specification language is established, creation of agents, abms, etc shall be specified in a declaration section (similar to ModelingToolkit.jl / Modelica etc.)
