### ISSUE TITLE
more general solution for modular agents?

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#23]
If we split agents into modules, such as kinship, demography, health, etc. functions that operate on these modules won't automatically work on composite agents. For example `add_child!(person)` would be defined with `person::Kinship` in mind. An agent that contains the kinship module would then have to forward the function call: `add_child!(person) = add_child!(person.kinship)`. This is very annoying at best and a source for errors at worst. Sadly Julia has neither mixins nor multiple inheritance so we have to find a solution ourselves.

I have a couple of ideas how to solve this (from simple naming conventions to meta-programming trickery) but in any case it would be nice to have a general solution.

**Comment by mhinsch** [comment]
Having 

```Julia
add_child!(p::Person) = add_child!(p.kinship)
```
would be the obvious way to handle these modules. However, I think that's not very satisfying since it means *every* function defined in *any* module has to be replicated in *every* definition of an agent type that uses that module.

**Comment by AtiyahElsheikh** [comment]
Ok. You may want to propose if this is milestone V0.X  or V{1,2}.X

**Comment by mhinsch** [comment]
Haven't tried it, but this looks like it might do exactly what we need: [https://github.com/JeffreySarnoff/TypedDelegation.jl](https://github.com/JeffreySarnoff/TypedDelegation.jl)
