### ISSUE TITLE
automatic code generation for unifying coding guidelines

### ISSUE THREAD

**Issue by AtiyahElsheikh** [MRC-CSO-SPHSU/LoneParentsModel.jl#26]
I feel the task of enhancing a package X with code like

```julia
[function] does_something() ... 
```
with an additional package Y that reads X and generates 

```julia
module Y

   using X 

   doesSomething(*) = does_something(*)

end 
```

Is somehow manageable? what do you think? 

related to issue #16

**Comment by mhinsch** [comment]
I don't think I understand what you mean. Do you want to automatise snake_case/camelCase?

**Comment by AtiyahElsheikh** [comment]
Yes to automatically generate separate code with consistent / desired coding conventions?

**Comment by mhinsch** [comment]
I know that some Ruby projects do that, but that seems like an awful lot of effort for something that's really only cosmetics. Can't we just adopt the "official" Julia style (which is basically what you have in your design document and what Agents.jl does as well)? Or if you really, really want camelCase go with that everywhere?
