### ISSUE TITLE
coding guidelines II

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#27]
While I very much prefer tabs over spaces, I can live with the latter. They should be used consistently, though. Currently some source files use 2 and some 4 spaces. Can we agree on 4?

**Comment by AtiyahElsheikh** [comment]
Ok I will attempt that. I am using VSCode and therefore not suffering from any inconsistencies in this regard. I will see if there is a setting for that and if there is any automatic tool for making the code consistent

**Comment by AtiyahElsheikh** [comment]
I have played with the settings of VSCode to ensure that tabsize would be 4. Still I won't be able to visually differentiate between spaces and tabs. Practically, I guess it would be difficult to ensure this consistency 100%, see e.g. [https://github.com/mhinsch/LoneParentsModel.jl/blob/agent_modules/src/agents/kinship.jl](https://github.com/mhinsch/LoneParentsModel.jl/blob/agent_modules/src/agents/kinship.jl ) ;-) (Probably you have just done copy and paste) 

How about using an automatic code formatter, e.g. [https://github.com/domluna/JuliaFormatter.jl](https://github.com/domluna/JuliaFormatter.jl) ? 
Should we use it manually on a regular basis? or shall we fine a way to integrate it at the pull-request phase?

**Comment by AtiyahElsheikh** [comment]
I can see white spaces but I cannot see difference between a tab and 4 spaces.
Thus,
Inserting tab = inserting 4 spaces
