### ISSUE TITLE
remove dependencies on MultiAgents, part II

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#28]
This is complete list of symbols that are still imported from MultiAgents. They should be moved to MainLPMMultiAgents.jl (or similar):

- [ ] ABM
- [ ] MultiABM
- [ ] MABMSimulation
- [ ] run!
- [ ] verify
- [x] read2DArray
- [x] date2yearsmonth
- [x] removefirst!
- [x] subtract!
- [ ] add_agent!
- [ ] dummystep
- [ ] defaultprestep!
- [ ] defaultpoststep!
- [ ] startTime
- [ ] dt
- [ ] attach_agent_step!
- [ ] attach_pre_model_step!
- [ ] attach_post_model_step!
- [ ] setup!
- [ ] allagents
- [ ] nagents
- [ ] initial_connect!
- [ ] attach2DData!
- [ ] AbstractExample
- [ ] AbstractAgent
- [ ] AbstractXAgent
- [ ] getIDCOUNTER
- [ ] kill_agent!

**Comment by AtiyahElsheikh** [comment]
This is a good idea to have such a separation. 
My suggestion would be however, to rather rename this repository to for instance MALPM.jl (don't like long names) and remove the agents/* and common code to LPM.jl  
I believe this would be much easier. 
Another reason: this repository has a history of 300 commits and so many tags. It is good to keep this history / tags for the older way and rather start a new repo with new history and tags etc. 
So is this ok?

**Comment by mhinsch** [comment]
My idea was to have a common repository that basically consists of three parts:
* the core model (LPM)
* a runnable version based on MultiAgents.jl
* a runnable version that's standalone and uses utility packages where necessary (e.g. MiniObserve)

But if you think that's more convenient we can also split out the core model into its own separate package. The main point I find important would be to (for now at least) avoid forking the core model.

**Comment by AtiyahElsheikh** [comment]
May be I have misunderstood you. Is it just renaming or restructuring? 
Restructuring would be error-prone. Separate package (or sub-package) would be easier to achieve the re-structuring in an incremental manner.

**Comment by AtiyahElsheikh** [comment]
[SomeUtil.jl](https://github.com/MRC-CSO-SPHSU/SomeUtil.jl) package. 
Feel free to suggest another name, or was the idea to have the utilities under LoneParentModels.Util module?

**Comment by mhinsch** [comment]
It's just a few bits and pieces anyway, so I think at this point it's probably easier to just keep the module within LPM.

**Comment by AtiyahElsheikh** [comment]
Well .. it can goes both ways: 

1. either remove MultiAgents-dependencies from LPM and additionally create MALPM 
2. or re-construct LPM from MALPM 

I felt it is more natural for option 2 due to high number of dependencies (all LPM/*.jl are MultiAgents-dependent).

I have created generic form of DoDeath!(*). It is still under MALPM.Simulate module. I was thinking to create a generic module Demography and put them there, what do you think or do you have better proposal?

**Comment by mhinsch** [comment]
Ah yes, that makes sense (option 2). Above I was referring to the Util module/package.

**Comment by AtiyahElsheikh** [comment]
> I have created generic form of DoDeath!(*). It is still under MALPM.Simulate module. I was thinking to create a generic module Demography and put them there, what do you think or do you have better proposal?

I have created LPM.Demography.Simulate module. This is just a suggestion as I don't find it necessary that it has to be 1-1 correspondence to MALPM module. May be you want to re-structure the naming of module? 

another issue: I know you don't like parameters as a dictionary. Well, I guess doDeath!(*) can be further flattened with named arguments? What do you think?

**Comment by mhinsch** [comment]
I think the easiest way to do it would be to have a generic function argument and then use struct member notification for simplicity and readability. So like this:

```Julia
function doDeaths!(population, params, verbose = true, sleeptime=0)
#...
    rawRate = params.baseDieProb + babyDieProb + ageDieProb
#...
end
```

Then if params is supposed to be a dictionary it's really simple to overload getproperty to access the dict content.

**Comment by AtiyahElsheikh** [comment]
> It's just a few bits and pieces anyway, so I think at this point it's probably easier to just keep the module within LPM.

I am actually making use of them within MultiAgents.jl

**Comment by AtiyahElsheikh** [comment]
So module LPM is supposed to be generic now?
