### ISSUE TITLE
@todo macro

### ISSUE THREAD

**Issue by AtiyahElsheikh** [MRC-CSO-SPHSU/LoneParentsModel.jl#31]
I thought since @assertion is under consideration, I believe @todo macro could be also similar and useful. Basically, @todo export reminder information about functionalities that need to be implemented. This is particularly useful for functions that cannot be implemented right away. 

A use-case (just as an example) , in the implementation of doDeath!(*) one makes use of many attributes of attributes of structs, e.g. person.info.alive. However, to make this function more generic, it would be better to have a function isAlive(person). I don't want to implement it myself right away myself, since I know you are working on that part of the code. 

Currently, I am expressing the need of that function using the following piece of code

```julia
...
false ? isAlive(person) : nothing 
# or 
age = false ? age(person) : person.info.age   
... 
```

**Comment by AtiyahElsheikh** [comment]
I found the [Todo package](https://github.com/analytech-solutions/Todo.jl) 
If nothing against? I am going to use it

**Comment by mhinsch** [comment]
It looks a bit unmaintained (last proper commit was 3 years ago), but sure why not.
