### ISSUE TITLE
death probability algorithm is probably wrong

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#34]
Assuming `deathProbability` returns the mortality *per year* the way it is used in `doDeath` is wrong. The probability per month can be calculated as p_m = 1- (1-p_y)^(1/12).

**Comment by AtiyahElsheikh** [comment]
I am not sure if this formula is embedded in [the Python version](cf. https://github.com/AtiyahElsheikh/Lone-Parents-Model/blob/main/sim.py#L1035) and I missed it in the translation?

If not, we need to include Umberto once he returns. You may want to consider another example, e.g. example=LPMUKDemographySuggested() with the correct formula and compare the plausibility of both versions?
