### ISSUE TITLE
Import vs. Using

### ISSUE THREAD

**Issue by AtiyahElsheikh** [MRC-CSO-SPHSU/LoneParentsModel.jl#41]
The book "Hands-on design patterns and best practices with Julia" recommends to employ` import` when a functionality is being extended, otherwise to employ `using` by default. This is so far the way I have followed.

**Comment by mhinsch** [comment]
Keep in mind that import and using have subtly different semantics. I think if we follow the rule that all imports have to be explicit (i.e. no using <modulename>) then we might just go the full way and prohibit import altogether (and use explicit name resolution for method definitions).

**Comment by AtiyahElsheikh** [comment]
I employ `using` also in an explicit way, e.g. 
`using Random: shuffle!`
