### ISSUE TITLE
styleguide: only use ?: to select values

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#47]
I think the use of ?: as an if-replacement is getting out of hand. It's really easy to skip over these lines and if you are - like me - used to the C/C++ use of ?: it automatically registers as non-modifying. There are some cases where it's nicer to use (modifying) ?: than if, but especially if one of the branches is empty I would really prefer it if we could stick with the boring option.

**Comment by AtiyahElsheikh** [comment]
So I usually make use of ? 
may be there are more potentials in current code and I am fine with that.

**Comment by AtiyahElsheikh** [comment]
I misunderstood you
I am fine with if rather than ?

**Comment by AtiyahElsheikh** [comment]
Will take little time before all ? are transformed to if

**Comment by mhinsch** [comment]
No worries, this is obviously low priority. Just maybe something to keep in mind.
