### ISSUE TITLE
LPM depends on AbstractAgent/AbstractXAgent

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#54]
As far as I can tell this this the last non-trivial dependency on MultiABM in LPM. Unfortunately I can't see a simple way to get rid of this (at least if we want to maintain compatibility of LPM with Agents.jl).

I can see two ways to do this:

1. Use a macro to make the superclass of all agent types generic (sadly this is not possible in plain Julia code, `struct T{S} <: S` does not work).
2. A multi-part process along these lines:
    - make Create/Initialize/etc. agent-type agnostic (maybe not a bad idea anyway), by using type parameters where necessary (function arguments declared as `::Type{T}` bind type `T` and can be called using the plain type, e.g. `Int`).
    - remove dependency on `XAgents` from `Demography`
    - move existing XAgents.jl to MALPMXAgents.jl and create generic XAgents.jl that declares dummy `AbstractAgent` and `AbstractXAgent` types
    - in modules LPM/MALPM include the respective XAgents module

**Comment by mhinsch** [comment]
Assuming the first step works out well, I prefer 2), as I think it's the cleaner solution.

**Comment by mhinsch** [comment]
Yet another (simpler) alternative would be to just remove the Demography module altogether and tie the various parts of the simulation together in LPM/MALPM. In that case modules in demography could keep their agent type dependencies.
On balance I think this is my preferred approach.

**Comment by AtiyahElsheikh** [comment]
I would understand your proposal better by example. 
But in general, I see that the solution should be simple and easy. In the mean time, we should be able to use our translated code.

**Comment by mhinsch** [comment]
I'll implement it in a branch so that you can have a look. I want to solve this now since I would like to have a running generic (i.e. non-Multi-Agent-dependent) version ASAP.

**Comment by AtiyahElsheikh** [comment]
Just all what I hope is to make use of Agents.jl. So I am fine whatever modifications make the code more generic, but still hoping it won't be too much further refactoring as a result.

**Comment by mhinsch** [comment]
[This](https://github.com/MRC-CSO-SPHSU/LoneParentsModel.jl/pull/55) is what I meant.

**Comment by AtiyahElsheikh** [comment]
I use Revise.jl 

At the moment I can run Main.jl multiple times. I can also run MainMALPM.jl multiple times. But I cannot switch between both in the same session. 

I get the following msg:

```
julia> include("MainMALPM.jl")
[ Info: Precompiling MALPM [top-level]
┌ Warning: Module XAgents with build ID 2066758737043071 is missing from the cache.
│ This may mean XAgents [top-level] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1107
[ Info: Skipping precompilation since __precompile__(false). Importing MALPM [top-level].
... 
```

If there is a simple solution for that, I am fine. Otherwise, I can live with it, e.g. two terminals.

**Comment by mhinsch** [comment]
I get the same warning (multiple times) when running either version from the terminal, but without further issues, so this seems not to be connected to the problem with Revise.
One issue might be that both versions of main now have to set *different* load paths since different versions of XAgents.jl need to be used. Assuming LOAD_PATH does not get reset between running the two different versions, the first one to be run will show up earlier in LOAD_PATH and its version of XAgents will keep getting loaded which of course does not work with the respective other version of main.
A simple fix would be to save LOAD_PATH before changing it and setting it back to the saved value after loading XAgents (at this point we might just as well start using relative import, though...).
