### ISSUE TITLE
naming convention for getters/setters

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#72]
Not terribly important, but just for the sake of completeness. My macros generate  property(obj) and property!(obj). If you'd rather use something more explicit (e.g. getProperty, setProperty!) now would be the time to say so (personally, I prefer the more concise version, but it's not something I can't live without).

**Comment by AtiyahElsheikh** [comment]
Would getProperty! , setProperty! somehow clash with the intention of base.[set/get]property!(*)

**Comment by mhinsch** [comment]
That was just by way of an example, just insert any property name for 'property' in my comment.
