### ISSUE TITLE
factor out iteration in model functions

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#74]
Not important now, but in the medium term it would be good to split model functions into the iteration part, that picks the agents to be modified and the actual modification that operates on single agents. E.g. (simplified example):
```Julia
function doAgeTransitions!(people, model, pars)
    for p in people
        ageTransition!(p, pars)
    end
end

function ageTransition!(person, pars)
     # all the important bits go here
end
```

That makes the model easier to read and modify (IMO) and would be needed anyway if we ever want to do an event-based version.

**Comment by AtiyahElsheikh** [comment]
Just remind me if I do a pull request that does not follow this pattern

**Comment by AtiyahElsheikh** [comment]
Question: 
You mentioned that the operator in is slow. Here it is used.

- In which context should in be avoided?
- What is the alternative?

**Comment by mhinsch** [comment]
I maybe said that in a misleading way. `in` itself isn't slow, but IIRC you used it to check whether an object was element of a collection. It's easy to forget that `in` simply iterates the vector until the element is found, so that check was a very slow operation.
