### ISSUE TITLE
add babies to population, families, links

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#76]

**Comment by mhinsch** [comment]
@AtiyahElsheikh I'll do that unless you already have started on it.

**Comment by AtiyahElsheikh** [comment]
The routine doBirths() (already pushed to develop) returns the new babies. The family links are estbalished within the function via the cor, see [this line](https://github.com/MRC-CSO-SPHSU/LoneParentsModel.jl/blob/develop/src/lpm/demography/Simulate.jl#L355).

**Comment by mhinsch** [comment]
Right, I didn't see the internal constructor in Person.

**Comment by AtiyahElsheikh** [comment]
Need to mentioned, the population is re-computed outside the routine by the called. So is the case also with doDeaths!()

**Comment by mhinsch** [comment]
Yes, I'm doing that in LPM as well now.
