### ISSUE TITLE
Statistics collections to be moved out of LPM/Simulate/*

### ISSUE THREAD

**Issue by AtiyahElsheikh** [MRC-CSO-SPHSU/LoneParentsModel.jl#80]
Apparently since there are nice ways to collect stats during a simulation, and also if working with lazy iterators, counting would be needed, then it seems better to not overload basic simulation functions such a responsibility.

**Comment by mhinsch** [comment]
Yes, absolutely agree on that. Verbose plus output should stay in, though.

**Comment by mhinsch** [comment]
For the plain version (LPM), I'll use [this](https://github.com/mhinsch/MiniObserve.jl).

**Comment by AtiyahElsheikh** [comment]
Yes .. verbose is there for debugging purposes
