### ISSUE TITLE
Julia 1.8.1 new features

### ISSUE THREAD

**Issue by AtiyahElsheikh** [MRC-CSO-SPHSU/LoneParentsModel.jl#85]
In the context of issue #79 , I thought to experiment with [Julia new features](https://julialang.org/blog/2022/08/julia-1.8-highlights/#new_allocation_profiler), particularly declaring some fields to mutable struct to be const. It did not improve the performance in this case, but it is a nice feature. Another feature is the ability to declare global types. 

Let me know if nothing against to use this feature

p.s. May be you know the [UpdateJulia package](https://github.com/LilithHafner/UpdateJulia.jl)

**Comment by mhinsch** [comment]
Fine with me, I wanted to switch to 1.8 anyway.
