### ISSUE TITLE
generic transition interface

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#87]
All population-wide transitions essentially do the same, so it makes sense to unify their interface. I have implemented that [here](https://github.com/mhinsch/LoneParentsModel.jl/tree/transitions) (in Main.jl, Utilities.jl and socialTransition.jl): A function applyTransitions (for now in Utilities.jl, should maybe be in some sort of Population module) applies a transition function (which operates on Person) and the usual parameters (model, verbose, parameters, etc.) to all elements of an iterable. The specific simulation module (in this case for example socialTransition) also provides a predicate (here selectSocialTransition) to select the agents the transition needs to be applied to.

**Comment by mhinsch** [comment]
Applied the same for age and work in the repo linked above.

**Comment by AtiyahElsheikh** [comment]
Looks good
