### ISSUE TITLE
parameter handling

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#96]
read/write to file, set via command line

**Comment by AtiyahElsheikh** [comment]
Via Parameters.jl? or something else

**Comment by mhinsch** [comment]
Doesn't do any of that, unfortunately. I have some code to convert between structs and command line arguments. It shouldn't be too much of an issue to extend it to for example read and write JSON.

For my previous project I used the parameter definitions (i.e. the Julia files they were defined in) as parameter files. That works quite well and has the additional advantage that (if parameters are not mutable) the compiler can do constant propagation and speed up some parts of the model (I think). 

Anyway, none of this is urgent in any way, it's just something that should happen at some point.
